name = "ArgusWrapper"
uuid = "07400ef0-896e-400f-8565-35c49d2738e4"
authors = ["IHP Systems R&D <research@ihp.dk>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"

[compat]
CxxWrap = "0.11.2"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
